//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Match.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Activity_detail = new HashSet<Activity_detail>();
        }

        [DisplayName("活動編號")]
        [Key]
        [RegularExpression("[A][0-9]{5}")]
        public string activity_id { get; set; }

        [DisplayName("類型編號")]
        [Required]
        [RegularExpression("[C][0-9]{2}")]
        public string activity_type_id { get; set; }

        [DisplayName("活動名稱")]
        [Required]
        [StringLength(50)]
        public string activity_name { get; set; }

        [DisplayName("活動日期")]
        [Required]
        [DataType(DataType.DateTime)]
        public System.DateTime activity_datetime { get; set; }

        [DisplayName("地點編號")]
        [Required]
        [RegularExpression("[S][0-9]{5}")]
        public string place_id { get; set; }

        [DisplayName("發起人編號")]
        [Required]
        [RegularExpression("[P][0-9]{5}")]
        public string member_id { get; set; }
    
        public virtual Activity_type Activity_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_detail> Activity_detail { get; set; }
        public virtual Member Member { get; set; }
        public virtual Place Place { get; set; }
    }
}



