//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Match.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Activity_detail
    {
        [DisplayName("流水號")]
        [Key]
        [RegularExpression("^[A][0-9]{12}$")]
        public string activity_detail_number { get; set; }

        [DisplayName("活動編號")]
        [RegularExpression("^[A][0-9]{5}$")]
        public string activity_id { get; set; }

        [DisplayName("參加者")]
        [RegularExpression("^[P][0-9]{5}$")]
        public string member_id { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Member Member { get; set; }
    }
}
