//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Match.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Activity = new HashSet<Activity>();
            this.Activity_detail = new HashSet<Activity_detail>();
            this.Friend = new HashSet<Friend>();
            this.Friend1 = new HashSet<Friend>();
        }

        [DisplayName("會員編號")]
        [Key]
        [RegularExpression("^[P][0-9]{5}$")]
        public string member_id { get; set; }

        [DisplayName("帳號")]
        [RegularExpression("^[A-Za-z0-9]{6,30}$")]
        public string member_account { get; set; }

        [DisplayName("密碼")]
        [RegularExpression("^[A-Za-z0-9]{6,30}$")]
        public string member_password { get; set; }

        [DisplayName("會員名稱")]
        [StringLength(50)]
        [Required]
        public string member_name { get; set; }

        [DisplayName("姓名")]
        [StringLength(20)]
        [Required]
        public string member_id_name { get; set; }

        [DisplayName("性別")]
        [RegularExpression("^[01]$")]
        public bool member_gender { get; set; }

        [DisplayName("生日")]
        [DataType(DataType.Date)]
        [Required]
        public System.DateTime member_birthday { get; set; }

        
        [DisplayName("手機號碼")]
        [RegularExpression("^[0][9][0-9]{8}$")]
        public string member_cellphone { get; set; }

        [DisplayName("電子信箱")]        
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        [StringLength(50)]
        [Required]
        public string member_email { get; set; }

        [DisplayName("通訊地址")]
        [StringLength(100)]
        [Required]
        public string member_address { get; set; }

        [DisplayName("權限編號")]
        [RegularExpression("^[A-Z]$")]
        public string right_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_detail> Activity_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friend1 { get; set; }
        public virtual Right Right { get; set; }
    }
}
