//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Match.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Security.Cryptography;

    [MetadataType(typeof(MetaMember))]

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Activity = new HashSet<Activity>();
            this.Activity_detail = new HashSet<Activity_detail>();
            this.Friend = new HashSet<Friend>();
            this.Friend1 = new HashSet<Friend>();
        }
    
        public string member_id { get; set; }
        public string member_account { get; set; }

        string password;  //定義一個password的field
        public string member_password
        {
            get
            {
                return password;

            }
            set
            {
                password = getHashPassword(value);
            }
        }
        public string member_name { get; set; }
        public string member_id_name { get; set; }
        public bool member_gender { get; set; }
        public System.DateTime member_birthday { get; set; }
        public string member_cellphone { get; set; }
        public string member_email { get; set; }
        public string member_address { get; set; }
        public string right_id { get; set; }
        public string member_photo_file { get; set; }
        public System.DateTime member_create_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_detail> Activity_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friend1 { get; set; }
        public virtual Right Right { get; set; }


        public static string getHashPassword(string pw)
        {
            byte[] hashValue;
            string result = "";

            System.Text.UnicodeEncoding ue = new System.Text.UnicodeEncoding();

            byte[] pwBytes = ue.GetBytes(pw);

            SHA256 shHash = SHA256.Create();

            hashValue = shHash.ComputeHash(pwBytes);

            foreach (byte b in hashValue)
            {
                result += b.ToString();
            }

            return result;
        }
    }
}
