//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Match.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetaPlace))]
    public partial class Place
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Place()
        {
            this.Activity = new HashSet<Activity>();
            this.Place_off_day = new HashSet<Place_off_day>();
        }
    
        public string place_id { get; set; }
        public string place_type_id { get; set; }
        public string shop_name { get; set; }
        public string place_address { get; set; }
        public string place_phone { get; set; }
        public Nullable<System.TimeSpan> place_hours_start { get; set; }
        public Nullable<System.TimeSpan> place_hours_end { get; set; }
        public System.DateTime place_create_date { get; set; }
        public string place_photo_file { get; set; }
        public bool place_shutdown { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Place_off_day> Place_off_day { get; set; }
        public virtual Place_type Place_type { get; set; }
    }
}
