//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _07ADOnet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class 教務系統Entities : DbContext
    {
        public 教務系統Entities()
            : base("name=教務系統Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<主管> 主管 { get; set; }
        public virtual DbSet<客戶> 客戶 { get; set; }
        public virtual DbSet<員工> 員工 { get; set; }
        public virtual DbSet<班級> 班級 { get; set; }
        public virtual DbSet<教授> 教授 { get; set; }
        public virtual DbSet<新客戶> 新客戶 { get; set; }
        public virtual DbSet<課程> 課程 { get; set; }
        public virtual DbSet<學生> 學生 { get; set; }
        public virtual DbSet<課程2> 課程2 { get; set; }
    
        [DbFunction("教務系統Entities", "fnStudentCourseQuery")]
        public virtual IQueryable<fnStudentCourseQuery_Result> fnStudentCourseQuery()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnStudentCourseQuery_Result>("[教務系統Entities].[fnStudentCourseQuery]()");
        }
    
        public virtual int drawStar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("drawStar");
        }
    
        public virtual int drawStar2(Nullable<int> c)
        {
            var cParameter = c.HasValue ?
                new ObjectParameter("c", c) :
                new ObjectParameter("c", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("drawStar2", cParameter);
        }
    
        public virtual ObjectResult<employeeDataRow_Result> employeeDataRow(Nullable<int> i, Nullable<int> j)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(int));
    
            var jParameter = j.HasValue ?
                new ObjectParameter("j", j) :
                new ObjectParameter("j", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<employeeDataRow_Result>("employeeDataRow", iParameter, jParameter);
        }
    
        public virtual ObjectResult<orderDetails_Result> orderDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<orderDetails_Result>("orderDetails");
        }
    }
}
