//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _07ADOnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 員工
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 員工()
        {
            this.教授 = new HashSet<教授>();
        }
    
        public string 身份證字號 { get; set; }
        public string 姓名 { get; set; }
        public string 城市 { get; set; }
        public string 街道 { get; set; }
        public string 電話 { get; set; }
        public Nullable<decimal> 薪水 { get; set; }
        public Nullable<decimal> 保險 { get; set; }
        public Nullable<decimal> 扣稅 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<教授> 教授 { get; set; }
    }
}
