//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _07ADOnet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class 教務系統Entities : DbContext
    {
        public 教務系統Entities()
            : base("name=教務系統Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<主管> 主管 { get; set; }
        public virtual DbSet<客戶> 客戶 { get; set; }
        public virtual DbSet<員工> 員工 { get; set; }
        public virtual DbSet<班級> 班級 { get; set; }
        public virtual DbSet<教授> 教授 { get; set; }
        public virtual DbSet<新客戶> 新客戶 { get; set; }
        public virtual DbSet<課程> 課程 { get; set; }
        public virtual DbSet<學生> 學生 { get; set; }
        public virtual DbSet<客戶業績> 客戶業績 { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<view有姓名的教授> view有姓名的教授 { get; set; }
    
        [DbFunction("教務系統Entities", "fnOffsetFetchNext")]
        public virtual IQueryable<fnOffsetFetchNext_Result> fnOffsetFetchNext(Nullable<int> m, Nullable<int> n)
        {
            var mParameter = m.HasValue ?
                new ObjectParameter("m", m) :
                new ObjectParameter("m", typeof(int));
    
            var nParameter = n.HasValue ?
                new ObjectParameter("n", n) :
                new ObjectParameter("n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnOffsetFetchNext_Result>("[教務系統Entities].[fnOffsetFetchNext](@m, @n)", mParameter, nParameter);
        }
    
        [DbFunction("教務系統Entities", "fnStudentCourseQuery")]
        public virtual IQueryable<fnStudentCourseQuery_Result> fnStudentCourseQuery()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnStudentCourseQuery_Result>("[教務系統Entities].[fnStudentCourseQuery]()");
        }
    
        [DbFunction("教務系統Entities", "fnStudentCourseQuery2")]
        public virtual IQueryable<fnStudentCourseQuery2_Result> fnStudentCourseQuery2(string stuID)
        {
            var stuIDParameter = stuID != null ?
                new ObjectParameter("StuID", stuID) :
                new ObjectParameter("StuID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnStudentCourseQuery2_Result>("[教務系統Entities].[fnStudentCourseQuery2](@StuID)", stuIDParameter);
        }
    
        public virtual ObjectResult<CourseDetails_Result> CourseDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CourseDetails_Result>("CourseDetails");
        }
    
        public virtual int drawStar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("drawStar");
        }
    
        public virtual int drawStar2(Nullable<int> c)
        {
            var cParameter = c.HasValue ?
                new ObjectParameter("c", c) :
                new ObjectParameter("c", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("drawStar2", cParameter);
        }
    
        public virtual ObjectResult<employeeDataRow_Result> employeeDataRow(Nullable<int> i, Nullable<int> j)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(int));
    
            var jParameter = j.HasValue ?
                new ObjectParameter("j", j) :
                new ObjectParameter("j", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<employeeDataRow_Result>("employeeDataRow", iParameter, jParameter);
        }
    
        public virtual int getCoursePivot()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getCoursePivot");
        }
    
        public virtual int Sum_for_Products_Salse_Pivot(Nullable<int> yy)
        {
            var yyParameter = yy.HasValue ?
                new ObjectParameter("yy", yy) :
                new ObjectParameter("yy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sum_for_Products_Salse_Pivot", yyParameter);
        }
    }
}
