//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _07ADOnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public string 身份證字號 { get; set; }
        public string 姓名 { get; set; }
        public string 城市 { get; set; }
        public string 街道 { get; set; }
        public string 電話 { get; set; }
        public Nullable<decimal> 薪水 { get; set; }
        public Nullable<decimal> 保險 { get; set; }
        public Nullable<decimal> 扣稅 { get; set; }
        public string 教授編號 { get; set; }
        public string 職稱 { get; set; }
        public string 科系 { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string 學號 { get; set; }
        public string 課程編號 { get; set; }
        public Nullable<System.DateTime> 上課時間 { get; set; }
        public string 教室 { get; set; }
        public string Expr3 { get; set; }
        public string 名稱 { get; set; }
        public Nullable<int> 學分 { get; set; }
        public string Expr4 { get; set; }
        public string Expr5 { get; set; }
        public string 性別 { get; set; }
        public string Expr6 { get; set; }
        public Nullable<System.DateTime> 生日 { get; set; }
    }
}
